### ISSUE TITLE
Add stuff from a reddit linke

### ISSUE THREAD

**Issue by aaomidi** [bo0tzz/TopKekBot#57]
Boet 'bo0tzz' de Willigen, [25.04.17 11:05]
How many babies does it take to paint a barn? 

D...
https://www.reddit.com/r/AskReddit/comments/67fzje/what_is_the_funniest_nsfw_joke_youve_ever_heard/

Boet 'bo0tzz' de Willigen, [25.04.17 11:05]
[In reply to Boet 'bo0tzz' de Willigen]
@aaomidi can you add the second one to @topkek_bot dad

**Comment by bo0tzz** [comment]
@aaomidi Thx dad
